### PR TITLE
fix for failing tests after name change + other stuff

### PR DESCRIPTION
**Pull request by orangewise**
Hi Anil,

after the name change, most of the tests were failing (if not all). That has been fixed in this PR. Besides that there is some new functionality as well. Maybe you can use it :)

### CODE REVIEW

**Comment by anil614sagar** [comment]
Thank you @orangewise , I am added you as collaborator to this project.  Feel free to push changes directly from now.

**Comment by anil614sagar** [comment]
@orangewise Let me know your npm username, i can add you there also so that you can able to publish new versions. Thank you again for valuable contributions.

**Comment by orangewise** [comment]
Thanks @anil614sagar, my npm username is robodo

**Comment by anil614sagar** [comment]
Done @orangewise , you now have access, https://www.npmjs.com/package/openapi2apigee

**Pull request merged**
